package Data_Persistence;

import java.io.*;
import java.util.*;

public class StudentRecord {

    private int id; // Unique autogenerated ID
    private String firstName;
    private String lastName;
    private String birthdate;
    private String address;
    private String guardian;
    private String regularContact;
    private String emergencyContact;

    // Static list to hold all student records
    public static ArrayList<StudentRecord> studentList = new ArrayList<>();
    
    private static final String MASTER_FILE = "Data/Student/Records/StudentRecord.txt";
    private static final String STUDENTS_LIST_FILE = "Data/Student/Records/StudentsList.txt";

    // Constructor for creating a new student record
    public StudentRecord(String firstName, String lastName, String birthdate, String address,
                         String guardian, String regularContact, String emergencyContact) {
        this.id = IDGenerator.generateID();
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthdate = birthdate;
        this.address = address;
        this.guardian = guardian;
        this.regularContact = regularContact;
        this.emergencyContact = emergencyContact;
        createStudentFile();
        studentList.add(this);
        appendToMasterFile();
        saveStudentNamesToFile();
    }
    
    // Constructor for loading a student record from file (ID is read from file)
    private StudentRecord(int id, String firstName, String lastName, String birthdate, String address,
                          String guardian, String regularContact, String emergencyContact, boolean isLoading) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthdate = birthdate;
        this.address = address;
        this.guardian = guardian;
        this.regularContact = regularContact;
        this.emergencyContact = emergencyContact;
        studentList.add(this);
    }
    
    private void createStudentFile() {
        String fileName = "Data/Student/Records/" + lastName + firstName + ".txt";
        File directory = new File("Data/Student/Records/");
        if (!directory.exists()) {
            directory.mkdirs();
        }
        File file = new File(fileName);
        try {
            if (file.createNewFile()) {
                System.out.println("File created for: " + firstName + " " + lastName);
            } else {
                System.out.println("File already exists for: " + firstName + " " + lastName);
            }
        } catch (IOException e) {
            System.out.println("Error creating file for " + firstName + " " + lastName + ": " + e.getMessage());
        }
    }
    
    // Save the student record to the master file including the unique ID
    private void appendToMasterFile() {
        File studentFile = new File(MASTER_FILE);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(studentFile, true))) {
            // Format: id|lastName|firstName|birthdate|address|guardian|regularContact|emergencyContact
            writer.write(id + "|" + lastName + "|" + firstName + "|" + birthdate + "|" + address + "|" + guardian + "|" + regularContact + "|" + emergencyContact);
            writer.newLine();
            System.out.println("Student saved to master file.");
        } catch (IOException e) {
            System.out.println("Error saving student to master file: " + e.getMessage());
        }
    }
    
    public static void loadStudentsFromFile() {
        studentList.clear();
        File masterFile = new File(MASTER_FILE);
        if (!masterFile.exists()){
            System.out.println("Master file does not exist.");
            return;
        }
        try (Scanner scanner = new Scanner(masterFile)) {
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                String[] tokens = line.split("\\|");
                // Expected tokens: id, lastName, firstName, birthdate, address, guardian, regularContact, emergencyContact
                if (tokens.length >= 8) {
                    int id = Integer.parseInt(tokens[0]);
                    new StudentRecord(id, tokens[2], tokens[1], tokens[3], tokens[4], tokens[5], tokens[6], tokens[7], true);
                }
            }
            System.out.println("Loaded students from master file.");
        } catch (IOException e) {
            System.out.println("Error loading students: " + e.getMessage());
        }
    }
    
    // This method returns a copy of the student list
    public static List<StudentRecord> getAllStudents() {
        return new ArrayList<>(studentList);
    }

    // New method: update the individual file with grade and teacher info.
    public void updateIndividualFile() {
        String fileName = "Data/Student/Records/" + lastName + firstName + ".txt";
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(fileName))) {
            writer.write("ID: " + id + "\n");
            writer.write("Name: " + firstName + " " + lastName + "\n");
            writer.write("Birthdate: " + birthdate + "\n");
            writer.write("Address: " + address + "\n");
            writer.write("Guardian: " + guardian + "\n");
            writer.write("Regular Contact: " + regularContact + "\n");
            writer.write("Emergency Contact: " + emergencyContact + "\n");
            writer.write("\n----- Grade & Teacher Info -----\n");
            
            // Retrieve the associated GradeRecord from GradeManager
            // (Make sure GradeManager is in the Application_Logic package)
            GradeRecord gr = Application_Logic.GradeManager.findGradeRecord(firstName, lastName);
            if (gr != null) {
                writer.write("Current Teacher: " + gr.getTeacherAssigned() + "\n");
                writer.write("Teacher History: " + gr.getTeacherHistory() + "\n");
                writer.write("Grades:\n" + gr.getGradesTable() + "\n");
            } else {
                writer.write("No grade record available.\n");
            }
        } catch (IOException e) {
            System.out.println("Error updating individual file for " + firstName + " " + lastName + ": " + e.getMessage());
        }
    }
    
    public static StudentRecord findStudent(String firstName, String lastName) {
        for (StudentRecord sr : studentList) {
            if (sr.firstName.equals(firstName) && sr.lastName.equals(lastName)) {
                return sr;
            }
        }
        return null;
    }
    
    public void updateStudent(String newFirstName, String newLastName, String newBirthdate, String newAddress,
                              String newGuardian, String newRegularContact, String newEmergencyContact) {
        this.firstName = newFirstName;
        this.lastName = newLastName;
        this.birthdate = newBirthdate;
        this.address = newAddress;
        this.guardian = newGuardian;
        this.regularContact = newRegularContact;
        this.emergencyContact = newEmergencyContact;
        rewriteMasterFile();
        saveStudentNamesToFile();
    }
    
    public void deleteStudent() {
        studentList.remove(this);
        String fileName = "Data/Student/Records/" + lastName + firstName + ".txt";
        File file = new File(fileName);
        if (file.exists() && file.delete()) {
            System.out.println("Deleted student file: " + fileName);
        } else {
            System.out.println("Failed to delete student file: " + fileName);
        }
        rewriteMasterFile();
        saveStudentNamesToFile();
    }
    
    private static void rewriteMasterFile() {
        File studentFile = new File(MASTER_FILE);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(studentFile))) {
            for (StudentRecord sr : studentList) {
                writer.write(sr.id + "|" +
                             sr.lastName + "|" +
                             sr.firstName + "|" +
                             sr.birthdate + "|" +
                             sr.address + "|" +
                             sr.guardian + "|" +
                             sr.regularContact + "|" +
                             sr.emergencyContact);
                writer.newLine();
            }
            System.out.println("Master file updated.");
        } catch (IOException e) {
            System.out.println("Error rewriting master file: " + e.getMessage());
        }
    }
    
    public static void saveStudentNamesToFile() {
        File studentsListFile = new File(STUDENTS_LIST_FILE);
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(studentsListFile))) {
            for (StudentRecord sr : studentList) {
                writer.write(sr.firstName + " " + sr.lastName);
                writer.newLine();
            }
            System.out.println("Student names saved to StudentsList.txt.");
        } catch (IOException e) {
            System.out.println("Error saving student names to file: " + e.getMessage());
        }
    }
    
    // Getters for the fields
    public int getId() {
        return id;
    }
    
    public String getFirstName() {
        return firstName;
    }
    
    public String getLastName() {
        return lastName;
    }
    
    public String getBirthdate() {
        return birthdate;
    }
    
    public String getAddress() {
        return address;
    }
    
    public String getGuardian() {
        return guardian;
    }
    
    public String getRegularContact() {
        return regularContact;
    }
    
    public String getEmergencyContact() {
        return emergencyContact;
    }
}
